"""changed_errors_structure_and_connections

Revision ID: 20c68d67a8d9
Revises: 762b46ecba2b
Create Date: 2026-08-30 15:15:38.901669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c68d67a8d9'
down_revision: Union[str, Sequence[str], None] = '762b46ecba2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempt_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['processing_attempts.id'], name=op.f('fk_attempt_errors_attempt_id_processing_attempts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempt_errors'))
    )
    op.drop_table('validation_errors')
    with op.batch_alter_table('hard_errors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_hard_errors_attempt_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_hard_errors_attempt_id_processing_attempts'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_hard_errors_request_id_requests'), 'requests', ['request_id'], ['id'])
        batch_op.drop_column('attempt_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hard_errors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_hard_errors_request_id_requests'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_hard_errors_attempt_id_processing_attempts'), 'processing_attempts', ['attempt_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_hard_errors_attempt_id'), ['attempt_id'])
        batch_op.drop_column('request_id')

    op.create_table('validation_errors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('thinking_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['thinking_id'], ['thinkings.id'], name=op.f('fk_validation_errors_thinking_id_thinkings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_errors'))
    )
    op.drop_table('attempt_errors')
    # ### end Alembic commands ###
