"""add_prompt_refs_to_requests_and_thinkings

Revision ID: 39003de3b10a
Revises: 783d13962185
Create Date: 2026-09-01 14:29:24.500170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39003de3b10a'
down_revision: Union[str, Sequence[str], None] = '783d13962185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_prompt_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_requests_selected_prompt_id_prompts'), 'prompts', ['selected_prompt_id'], ['id'])

    with op.batch_alter_table('thinkings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_prompt_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_thinkings_used_prompt_id_prompts'), 'prompts', ['used_prompt_id'], ['id'])

    op.execute("UPDATE thinkings SET used_prompt_id = 1")

    with op.batch_alter_table('thinkings', schema=None) as batch_op:
        batch_op.alter_column('used_prompt_id', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thinkings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_thinkings_used_prompt_id_prompts'), type_='foreignkey')
        batch_op.drop_column('used_prompt_id')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_requests_selected_prompt_id_prompts'), type_='foreignkey')
        batch_op.drop_column('selected_prompt_id')

    # ### end Alembic commands ###
