"""drop request, queue-based attempts

Revision ID: 3c2cf9aa04a5
Revises: fe4a9889f457
Create Date: 2026-09-15 17:28:42.811851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2cf9aa04a5'
down_revision: Union[str, Sequence[str], None] = 'fe4a9889f457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('hard_errors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_hard_errors_request_id_requests'), type_='foreignkey')
        batch_op.drop_column('request_id')

    with op.batch_alter_table('processing_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_processing_attempts_request_id_requests'), type_='foreignkey')
        batch_op.drop_column('request_id')

    op.drop_table('requests')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_processing_attempts_request_id_requests'), 'requests', ['request_id'], ['id'])

    with op.batch_alter_table('hard_errors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_hard_errors_request_id_requests'), 'requests', ['request_id'], ['id'])

    op.create_table('requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('titles_amount', sa.INTEGER(), nullable=False),
    sa.Column('elapsed_time', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('selected_prompt_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['selected_prompt_id'], ['prompts.id'], name=op.f('fk_requests_selected_prompt_id_prompts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests')),
    sa.UniqueConstraint('uuid', name=op.f('uq_requests_uuid'))
    )
    # ### end Alembic commands ###
