"""add_attempt_status_and_nullable_elapsed_time

Revision ID: 762b46ecba2b
Revises: f2285e7d7cd8
Create Date: 2026-08-29 18:12:16.899893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762b46ecba2b'
down_revision: Union[str, Sequence[str], None] = 'f2285e7d7cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='attempt_status', native_enum=False), nullable=False))
        batch_op.create_index(batch_op.f('ix_processing_attempts_status'), ['status'], unique=False)

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.alter_column('elapsed_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.alter_column('elapsed_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('processing_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_attempts_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
