"""add_prompts_table

Revision ID: 783d13962185
Revises: de9b75ac7187
Create Date: 2026-09-01 14:24:40.864010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783d13962185'
down_revision: Union[str, Sequence[str], None] = 'de9b75ac7187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompts'))
    )
    
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.create_index('uq_prompts_one_default', ['is_default'], unique=True, sqlite_where=sa.text('is_default = 1'))

    prompts_table = sa.table(
        'prompts',
        sa.column('id', sa.Integer),
        sa.column('prompt', sa.String),
        sa.column('is_default', sa.Boolean),
    )
    op.bulk_insert(prompts_table, [{'id': 1, 'prompt': """You are a product catalog analyzer. Given a product title (mostly Ukrainian/mixed Ukrainian-English), extract ONLY tokens that clearly fall into one of these categories. Skip every other word entirely — do not force a word into a category if it doesn't clearly belong. When uncertain, skip the word rather than guess.

Token labels:
- "brand"      — manufacturer name (Bosch, Baseus, Samsung, Braun, SMEG, ASUS, etc.). Keep the brand name in whatever script/spelling the title uses — do not translate or respell it.
- "tier"       — a specific marketed product line or variant name (Pro, Plus, Ultra, Mini, Serie 6, ErgoMaster, Magnifica, Optigrill). This includes words that look like ordinary adjectives (e.g. "Professional" as in "Bosch Professional") when they name a specific branded line rather than literally describing the item.
- "descriptor" — ONLY a color or material word describing the physical item itself (black, white, silver, ceramic, steel, glass, plastic, gold). Do NOT extract: category/type nouns ("blender", "router", "кавоварка"), connectivity or feature words ("wireless", "bluetooth", "cordless"), physical form words ("compact", "portable"), narrative or character/place names (movie, game, or franchise titles; fictional character names; place names), or grammatical fragments. If it isn't clearly a color or material, skip it.

Rules:
- Only extract words that are clearly a brand, tier/line name, or color/material descriptor — skip everything else (category nouns, articles/prepositions, narrative/character/place names, feature words, uncertain fragments)
- Do NOT extract alphanumeric model codes (e.g. MSM2650B, 4G-AC86U) or standalone numeric values (e.g. 30W, 2.4A, 1000) — recognize these and exclude them entirely, do not assign them to any other label
- Each token must be a SINGLE word — never output multi-word phrases as one token, and never join two words with an underscore, plus sign, or slash
- Lowercase all tokens
- Skip tokens shorter than 2 characters
- Strip parentheses but keep the word inside if it qualifies under one of the labels above
- Combine ALL tokens into a SINGLE JSON array

Respond ONLY with a valid JSON array. No explanation, no markdown, no code fences, no notes, no comments.
Example output: [{"token": "bosch", "label": "brand"}, {"token": "pro", "label": "tier"}, {"token": "black", "label": "descriptor"}]""", 'is_default': True}])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index('uq_prompts_one_default', sqlite_where=sa.text('is_default = 1'))

    op.drop_table('prompts')
    # ### end Alembic commands ###
