"""split_thinking_token_counts

Revision ID: 97ea8a9f72eb
Revises: 2c935430d340
Create Date: 2026-08-30 16:19:36.962840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ea8a9f72eb'
down_revision: Union[str, Sequence[str], None] = '2c935430d340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thinkings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_tokens', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('completion_tokens', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reasoning_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('finish_reason', sa.String(), nullable=False))
        batch_op.drop_column('tokens')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thinkings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens', sa.INTEGER(), nullable=False))
        batch_op.drop_column('finish_reason')
        batch_op.drop_column('reasoning_tokens')
        batch_op.drop_column('completion_tokens')
        batch_op.drop_column('prompt_tokens')

    # ### end Alembic commands ###
