"""add_thinking_duration_column

Revision ID: de9b75ac7187
Revises: 97ea8a9f72eb
Create Date: 2026-08-30 20:22:29.701794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9b75ac7187'
down_revision: Union[str, Sequence[str], None] = '97ea8a9f72eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thinkings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Interval(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thinkings', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
