"""add_title_brands_processing_attempts_occurrence_and_timestamps

Revision ID: f2285e7d7cd8
Revises: 
Create Date: 2026-08-29 15:03:55.995332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2285e7d7cd8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('occurrence', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('name', name=op.f('uq_brands_name'))
    )
    op.create_table('descriptors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('occurrence', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_descriptors')),
    sa.UniqueConstraint('name', name=op.f('uq_descriptors_name'))
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('titles_amount', sa.Integer(), nullable=False),
    sa.Column('elapsed_time', sa.Interval(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests')),
    sa.UniqueConstraint('uuid', name=op.f('uq_requests_uuid'))
    )
    op.create_table('tier_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('occurrence', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tier_words')),
    sa.UniqueConstraint('name', name=op.f('uq_tier_words_name'))
    )
    op.create_table('brand_tier',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('tier_word_id', sa.Integer(), nullable=False),
    sa.Column('occurrence', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_tier_brand_id_brands')),
    sa.ForeignKeyConstraint(['tier_word_id'], ['tier_words.id'], name=op.f('fk_brand_tier_tier_word_id_tier_words')),
    sa.PrimaryKeyConstraint('brand_id', 'tier_word_id', name=op.f('pk_brand_tier'))
    )
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_titles_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_titles')),
    sa.UniqueConstraint('title', name=op.f('uq_titles_title'))
    )
    op.create_table('processing_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_processing_attempts_request_id_requests')),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], name=op.f('fk_processing_attempts_title_id_titles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_attempts'))
    )
    op.create_table('title_brands',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_title_brands_brand_id_brands')),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], name=op.f('fk_title_brands_title_id_titles')),
    sa.PrimaryKeyConstraint('title_id', 'brand_id', name=op.f('pk_title_brands'))
    )
    op.create_table('title_descriptors',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('descriptor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['descriptor_id'], ['descriptors.id'], name=op.f('fk_title_descriptors_descriptor_id_descriptors')),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], name=op.f('fk_title_descriptors_title_id_titles')),
    sa.PrimaryKeyConstraint('title_id', 'descriptor_id', name=op.f('pk_title_descriptors'))
    )
    op.create_table('title_tier_words',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('tier_word_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tier_word_id'], ['tier_words.id'], name=op.f('fk_title_tier_words_tier_word_id_tier_words')),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], name=op.f('fk_title_tier_words_title_id_titles')),
    sa.PrimaryKeyConstraint('title_id', 'tier_word_id', name=op.f('pk_title_tier_words'))
    )
    op.create_table('hard_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['processing_attempts.id'], name=op.f('fk_hard_errors_attempt_id_processing_attempts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hard_errors')),
    sa.UniqueConstraint('attempt_id', name=op.f('uq_hard_errors_attempt_id'))
    )
    op.create_table('thinkings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['processing_attempts.id'], name=op.f('fk_thinkings_attempt_id_processing_attempts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thinkings')),
    sa.UniqueConstraint('attempt_id', name=op.f('uq_thinkings_attempt_id'))
    )
    op.create_table('validation_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thinking_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['thinking_id'], ['thinkings.id'], name=op.f('fk_validation_errors_thinking_id_thinkings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_errors'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_errors')
    op.drop_table('thinkings')
    op.drop_table('hard_errors')
    op.drop_table('title_tier_words')
    op.drop_table('title_descriptors')
    op.drop_table('title_brands')
    op.drop_table('processing_attempts')
    op.drop_table('titles')
    op.drop_table('brand_tier')
    op.drop_table('tier_words')
    op.drop_table('requests')
    op.drop_table('descriptors')
    op.drop_table('brands')
    # ### end Alembic commands ###
