"""drop_title_request_and_occurrence

Revision ID: fe4a9889f457
Revises: 39003de3b10a
Create Date: 2026-09-05 12:23:45.059226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4a9889f457'
down_revision: Union[str, Sequence[str], None] = '39003de3b10a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand_tier')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_column('occurrence')

    with op.batch_alter_table('descriptors', schema=None) as batch_op:
        batch_op.drop_column('occurrence')

    with op.batch_alter_table('tier_words', schema=None) as batch_op:
        batch_op.drop_column('occurrence')

    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_titles_request_id_requests'), type_='foreignkey')
        batch_op.drop_column('request_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_titles_request_id_requests'), 'requests', ['request_id'], ['id'])

    with op.batch_alter_table('tier_words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occurrence', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))

    with op.batch_alter_table('descriptors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occurrence', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occurrence', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))

    op.create_table('brand_tier',
    sa.Column('brand_id', sa.INTEGER(), nullable=False),
    sa.Column('tier_word_id', sa.INTEGER(), nullable=False),
    sa.Column('occurrence', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_tier_brand_id_brands')),
    sa.ForeignKeyConstraint(['tier_word_id'], ['tier_words.id'], name=op.f('fk_brand_tier_tier_word_id_tier_words')),
    sa.PrimaryKeyConstraint('brand_id', 'tier_word_id', name=op.f('pk_brand_tier'))
    )
    # ### end Alembic commands ###
